### ISSUE TITLE
Live updates

### ISSUE THREAD

**Issue by lurk24** [mjungnickel18/papyruscs#30]
Is there any suggestions or guidance for running this against a live server, or best practices for getting updated maps throughout the day for an active server?

**Comment by Christian7573** [comment]
Papyrus currently does not support running on a live server due to a limitation of LevelDB, the world format that Minecraft: Bedrock Edition uses. It only allows one program to be opening a database at a time, obviously a problem when both a Minecraft server and papyrus are trying to access a world.

If you're handy with scripts, you can set up one that stops the server, copies the world, restarts the server, and runs papyrus at the same time on the copy for minimal downtime. I believe there's a mechanism in place to prevent papyrus from redrawing unchanged chunks, can't remember though.

**Comment by lurk24** [comment]
cool, thanks, i made a script that does exactly as you suggested. For now that works, but it kicks off everyone that is connected when it runs. So i will schedule it to run periodically.

Ideally some sort of live-updating would be really cool, but i understand if it is outside of the scope of this project.
