### ISSUE TITLE
Trying to figure out how to share the map online like the example.

### ISSUE THREAD

**Issue by HereToHelp777** [mjungnickel18/papyruscs#66]
I run a MC realm and want to share the map to my members but for the life of me I can not figure out how to share the file publicly.

I tried google drive, and even Weebly to host it but it just comes up as a black screen. I'm assuming it needs the tiles to support the map?

I'm hoping this is the right place to ask for help. I don't know anything about GitHub or any of this kind of stuff really.

Any help would be immensely appreciated
Thank you for building an awesome program and thank you for your time!

**Comment by clarkx86** [comment]
Hello,
first of all I would really recommend joining our [dedicated Discord server](https://discord.com/invite/J2sBaXa), where this exact topic has been discussed recently as well :).
The reason why Google Drive won't work is because in order to host a map you would need a web server (apache, nginx, etc.) to properly serve the tiles. I don't know anything about Weebly, but you would either need to host your own VPS (there are countless providers available, given you have some experience in using Linux) or find a web-hosting service which gives you FTP-access to it's web-server. Then, because the maps can get quite large, you would either need to reduce the image quality using the `-f` and `-q` flags or find a provider which gives you a lot of storage.

**Comment by HereToHelp777** [comment]
Thank you very much for the response! I'll definitely look in to all of that.
